# Generated by Django 2.2.1 on 2019-05-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190512_0727'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='like',
        ),
    ]
